from funcoes import mensagem_inicial, definicao_taxa, espaco_estado, espaco_resultado, definicao_texto_taxa, calculo_por_hab

mensagem_inicial()
multiplicador = definicao_taxa()
print(multiplicador)

lista_estados = {"ac": "Acre ", "al": "Alagoas ", "am": "Amazonas ", "ap": "Amapá ", "ba": "Bahia ", "ce": "Ceára ", "df": "Distrito Federal ", "es": "Espírito Santo ", "go": "Góias ", "ma": "Maranhão ", "mg": "Minas Gerais ", "ms": "Mato Grosso do Sul ","mt": "Mato Grosso ","pa": "Pará ","pb": "Paraíba ","pe": "Pernambuco ","pi": "Piauí ","pr": "Paraná ","rj": "Rio de Janeiro ", "rn": "Rio Grande do Norte ", "rs": "Rio Grande do Sul ", "ro": "Rondônia ", "rr": "Roraima ", "sc": "Santa Catarina ", "se": "Sergipe ", "sp": "São Paulo ", "to": "Tocantins "}

print("Número de óbitos no Estado/DF: \n")
ac = int(input(lista_estados["ac"])); al = int(input(lista_estados["al"])); am = int(input(lista_estados["am"])); ap = int(input(lista_estados["ap"])); ba = int(input(lista_estados["ba"])); ce = int(input(lista_estados["ce"])); df = int(input(lista_estados["df"])); es = int(input(lista_estados["es"])); go = int(input(lista_estados["go"])); ma = int(input(lista_estados["ma"])); mg = int(input(lista_estados["mg"])); ms = int(input(lista_estados["ms"])); mt = int(input(lista_estados["mt"])); pa = int(input(lista_estados["pa"])); pb = int(input(lista_estados["pb"])); pe = int(input(lista_estados["pe"])); pi = int(input(lista_estados["pi"])); pr = int(input(lista_estados["pr"])); rj = int(input(lista_estados["rj"])); rn = int(input(lista_estados["rn"])); rs = int(input(lista_estados["rs"])); ro = int(input(lista_estados["ro"])); rr = int(input(lista_estados["rr"])); sc = int(input(lista_estados["sc"])); se = int(input(lista_estados["se"])); sp = int(input(lista_estados["sp"])); to = int(input(lista_estados["to"]));

pop_estados = {"pop_ac": 881935, "pop_al": 3337357, "pop_am": 4144597,"pop_ap": 845731, "pop_ba": 14873064, "pop_ba": 14873064, "pop_ce": 9132078, "pop_df": 3015268, "pop_es": 4018650, "pop_go": 7018354, "pop_ma": 7075181, "pop_mg": 21168791, "pop_ms": 2778986, "pop_mt": 3484466, "pop_pa": 8602865, "pop_pb": 4018127, "pop_pe": 9557071, "pop_pi": 3273227, "pop_pr": 11433957, "pop_rj": 17264943, "pop_rn": 3506853, "pop_rs": 11377239, "pop_ro": 1777225, "pop_rr": 605761, "pop_sc": 7164788, "pop_se": 2298696, "pop_sp": 45919049, "pop_to": 1572866}

obitos_estados = {"obitos_ac": ac, "obitos_al": al, "obitos_am": am, "obitos_ap": ap, "obitos_ba": ba, "obitos_ce": ce, "obitos_df": df, "obitos_es": es, "obitos_go": go, "obitos_ma": ma, "obitos_mg": mg, "obitos_ms": ms, "obitos_mt": mt, "obitos_pa": pa, "obitos_pb": pb, "obitos_pe": pe, "obitos_pi": pi, "obitos_pr": pr, "obitos_rj": rj, "obitos_rn": rn, "obitos_rs": rs, "obitos_ro": ro, "obitos_rr": rr, "obitos_sc": sc, "obitos_se": se, "obitos_sp": sp, "obitos_to": to}

obitos_por_pop_ac = calculo_por_hab(obitos_estados["obitos_ac"], pop_estados["pop_ac"], multiplicador); obitos_por_pop_al = calculo_por_hab(obitos_estados["obitos_al"], pop_estados["pop_al"], multiplicador); obitos_por_pop_am = calculo_por_hab(obitos_estados["obitos_am"], pop_estados["pop_am"], multiplicador); obitos_por_pop_ap = calculo_por_hab(obitos_estados["obitos_ap"], pop_estados["pop_ap"], multiplicador); obitos_por_pop_ba = calculo_por_hab(obitos_estados["obitos_ba"], pop_estados["pop_ba"], multiplicador); obitos_por_pop_ce = calculo_por_hab(obitos_estados["obitos_ce"], pop_estados["pop_ce"], multiplicador); obitos_por_pop_df = calculo_por_hab(obitos_estados["obitos_df"], pop_estados["pop_df"], multiplicador); obitos_por_pop_es = calculo_por_hab(obitos_estados["obitos_es"], pop_estados["pop_es"], multiplicador); obitos_por_pop_go = calculo_por_hab(obitos_estados["obitos_go"], pop_estados["pop_go"], multiplicador); obitos_por_pop_ma = calculo_por_hab(obitos_estados["obitos_ma"], pop_estados["pop_ma"], multiplicador); obitos_por_pop_mg = calculo_por_hab(obitos_estados["obitos_mg"], pop_estados["pop_mg"], multiplicador); obitos_por_pop_ms = calculo_por_hab(obitos_estados["obitos_ms"], pop_estados["pop_ms"], multiplicador); obitos_por_pop_mt = calculo_por_hab(obitos_estados["obitos_mt"], pop_estados["pop_mt"], multiplicador); obitos_por_pop_pa = calculo_por_hab(obitos_estados["obitos_pa"], pop_estados["pop_pa"], multiplicador); obitos_por_pop_pb = calculo_por_hab(obitos_estados["obitos_pb"], pop_estados["pop_pb"], multiplicador); obitos_por_pop_pe = calculo_por_hab(obitos_estados["obitos_pe"], pop_estados["pop_pe"], multiplicador); obitos_por_pop_pi = calculo_por_hab(obitos_estados["obitos_pi"], pop_estados["pop_pi"], multiplicador); obitos_por_pop_pr = calculo_por_hab(obitos_estados["obitos_pr"], pop_estados["pop_pr"], multiplicador); obitos_por_pop_rj = calculo_por_hab(obitos_estados["obitos_rj"], pop_estados["pop_rj"], multiplicador); obitos_por_pop_rn = calculo_por_hab(obitos_estados["obitos_rn"], pop_estados["pop_rn"], multiplicador); obitos_por_pop_rs = calculo_por_hab(obitos_estados["obitos_rs"], pop_estados["pop_rs"], multiplicador); obitos_por_pop_ro = calculo_por_hab(obitos_estados["obitos_ro"], pop_estados["pop_ro"], multiplicador); obitos_por_pop_rr = calculo_por_hab(obitos_estados["obitos_rr"], pop_estados["pop_rr"], multiplicador); obitos_por_pop_sc = calculo_por_hab(obitos_estados["obitos_sc"], pop_estados["pop_sc"], multiplicador); obitos_por_pop_se = calculo_por_hab(obitos_estados["obitos_se"], pop_estados["pop_se"], multiplicador); obitos_por_pop_sp = calculo_por_hab(obitos_estados["obitos_sp"], pop_estados["pop_sp"], multiplicador); obitos_por_pop_to = calculo_por_hab(obitos_estados["obitos_to"], pop_estados["pop_to"], multiplicador);

arredondamento = 2
lista_obitos_por_pop_estados = {"ac": round(obitos_por_pop_ac,arredondamento), "al": round(obitos_por_pop_al,arredondamento), "am": round(obitos_por_pop_am,arredondamento), "ap": round(obitos_por_pop_ap,arredondamento), "ba": round(obitos_por_pop_ba,arredondamento), "ce": round(obitos_por_pop_ce,arredondamento), "df": round(obitos_por_pop_df,arredondamento), "es": round(obitos_por_pop_es,arredondamento), "go": round(obitos_por_pop_go,arredondamento), "ma": round(obitos_por_pop_ma,arredondamento), "mg": round(obitos_por_pop_mg,arredondamento), "ms": round(obitos_por_pop_ms,arredondamento), "mt": round(obitos_por_pop_mt,arredondamento), "pa": round(obitos_por_pop_pa,arredondamento), "pb": round(obitos_por_pop_pb,arredondamento), "pe": round(obitos_por_pop_pe,arredondamento), "pi": round(obitos_por_pop_pi,arredondamento), "pr": round(obitos_por_pop_pr,arredondamento), "rj": round(obitos_por_pop_rj,arredondamento), "rn": round(obitos_por_pop_rn,arredondamento), "rs": round(obitos_por_pop_rs,arredondamento), "ro": round(obitos_por_pop_ro,arredondamento), "rr": round(obitos_por_pop_rr,arredondamento), "sc": round(obitos_por_pop_sc,arredondamento), "se": round(obitos_por_pop_se,arredondamento), "sp": round(obitos_por_pop_sp,arredondamento), "to": round(obitos_por_pop_to,arredondamento)}
obitos_por_pop_keys = lista_obitos_por_pop_estados.keys()
obitos_por_pop_values = lista_obitos_por_pop_estados.values()
#sorted(obitos_por_pop_values)

pairs = zip(obitos_por_pop_values(), obitos_por_pop_keys())
print(pairs)




#print(sorted(lista_obitos_por_pop_estados, key = lambda obitos_por_hab: obitos_por_hab[0]))
#print(lista_obitos_por_pop_estados)

texto_taxa = definicao_texto_taxa(multiplicador)

barra_vertical = "|"
barra_horizontal = "-"

lista_carac_estados = {"ac": espaco_estado(lista_estados["ac"]), "al": espaco_estado(lista_estados["al"]), "am": espaco_estado(lista_estados["am"]), "ap": espaco_estado(lista_estados["ap"]), "ba": espaco_estado(lista_estados["ba"]), "ce": espaco_estado(lista_estados["ce"]), "df": espaco_estado(lista_estados["df"]), "es": espaco_estado(lista_estados["es"]), "go": espaco_estado(lista_estados["go"]), "ma": espaco_estado(lista_estados["ma"]), "mg": espaco_estado(lista_estados["mg"]), "ms": espaco_estado(lista_estados["ms"]), "mt": espaco_estado(lista_estados["mt"]), "pa": espaco_estado(lista_estados["pa"]), "pb": espaco_estado(lista_estados["pb"]), "pe": espaco_estado(lista_estados["pe"]), "pi": espaco_estado(lista_estados["pi"]), "pr": espaco_estado(lista_estados["pr"]), "rj": espaco_estado(lista_estados["rj"]), "rn": espaco_estado(lista_estados["rn"]), "rs": espaco_estado(lista_estados["rs"]), "ro": espaco_estado(lista_estados["ro"]), "rr": espaco_estado(lista_estados["rr"]), "sc": espaco_estado(lista_estados["sc"]), "se": espaco_estado(lista_estados["se"]), "sp": espaco_estado(lista_estados["sp"]), "to": espaco_estado(lista_estados["to"])}
lista_carac_resultado = {"ac": espaco_resultado(lista_obitos_por_pop_estados["ac"]), "al": espaco_resultado(lista_obitos_por_pop_estados["al"]), "am": espaco_resultado(lista_obitos_por_pop_estados["am"]), "ap": espaco_resultado(lista_obitos_por_pop_estados["ap"]), "ba": espaco_resultado(lista_obitos_por_pop_estados["ba"]), "ce": espaco_resultado(lista_obitos_por_pop_estados["ce"]), "df": espaco_resultado(lista_obitos_por_pop_estados["df"]), "es": espaco_resultado(lista_obitos_por_pop_estados["es"]), "go": espaco_resultado(lista_obitos_por_pop_estados["go"]), "ma": espaco_resultado(lista_obitos_por_pop_estados["ma"]), "mg": espaco_resultado(lista_obitos_por_pop_estados["mg"]), "ms": espaco_resultado(lista_obitos_por_pop_estados["ms"]), "mt": espaco_resultado(lista_obitos_por_pop_estados["mt"]), "pa": espaco_resultado(lista_obitos_por_pop_estados["pa"]), "pb": espaco_resultado(lista_obitos_por_pop_estados["pb"]), "pe": espaco_resultado(lista_obitos_por_pop_estados["pe"]), "pi": espaco_resultado(lista_obitos_por_pop_estados["pi"]), "pr": espaco_resultado(lista_obitos_por_pop_estados["pr"]), "rj": espaco_resultado(lista_obitos_por_pop_estados["rj"]), "rn": espaco_resultado(lista_obitos_por_pop_estados["rn"]), "rs": espaco_resultado(lista_obitos_por_pop_estados["rs"]), "ro": espaco_resultado(lista_obitos_por_pop_estados["ro"]), "rr": espaco_resultado(lista_obitos_por_pop_estados["rr"]), "sc": espaco_resultado(lista_obitos_por_pop_estados["sc"]), "se": espaco_resultado(lista_obitos_por_pop_estados["se"]), "sp": espaco_resultado(lista_obitos_por_pop_estados["sp"]), "to": espaco_resultado(lista_obitos_por_pop_estados["to"])}

print("\nSegue a lista dos Estados e o DF com a {}:".format(texto_taxa))
print(barra_horizontal*35)
print(barra_vertical,lista_estados["ac"],lista_carac_estados["ac"],barra_vertical,lista_carac_resultado["ac"],lista_obitos_por_pop_estados["ac"],barra_vertical)
print(barra_vertical,lista_estados["al"],lista_carac_estados["al"],barra_vertical,lista_carac_resultado["al"],lista_obitos_por_pop_estados["al"],barra_vertical)
print(barra_vertical,lista_estados["am"],lista_carac_estados["am"],barra_vertical,lista_carac_resultado["am"],lista_obitos_por_pop_estados["am"],barra_vertical)
print(barra_vertical,lista_estados["ap"],lista_carac_estados["ap"],barra_vertical,lista_carac_resultado["ap"],lista_obitos_por_pop_estados["ap"],barra_vertical)
print(barra_vertical,lista_estados["ba"],lista_carac_estados["ba"],barra_vertical,lista_carac_resultado["ba"],lista_obitos_por_pop_estados["ba"],barra_vertical)
#print(barra_vertical,lista_estados["ce"],lista_carac_estados["ce"],barra_vertical,lista_carac_resultado["ce"],lista_obitos_por_pop_estados["ce"],barra_vertical)
#print(barra_vertical,lista_estados["df"],lista_carac_estados["df"],barra_vertical,lista_carac_resultado["df"],lista_obitos_por_pop_estados["df"],barra_vertical)
#print(barra_vertical,lista_estados["es"],lista_carac_estados["es"],barra_vertical,lista_carac_resultado["es"],lista_obitos_por_pop_estados["es"],barra_vertical)
#print(barra_vertical,lista_estados["go"],lista_carac_estados["go"],barra_vertical,lista_carac_resultado["go"],lista_obitos_por_pop_estados["go"],barra_vertical)
#print(barra_vertical,lista_estados["ma"],lista_carac_estados["ma"],barra_vertical,lista_carac_resultado["ma"],lista_obitos_por_pop_estados["ma"],barra_vertical)
#print(barra_vertical,lista_estados["mg"],lista_carac_estados["mg"],barra_vertical,lista_carac_resultado["mg"],lista_obitos_por_pop_estados["mg"],barra_vertical)
#print(barra_vertical,lista_estados["ms"],lista_carac_estados["ms"],barra_vertical,lista_carac_resultado["ms"],lista_obitos_por_pop_estados["ms"],barra_vertical)
#print(barra_vertical,lista_estados["mt"],lista_carac_estados["mt"],barra_vertical,lista_carac_resultado["mt"],lista_obitos_por_pop_estados["mt"],barra_vertical)
#print(barra_vertical,lista_estados["pa"],lista_carac_estados["pa"],barra_vertical,lista_carac_resultado["pa"],lista_obitos_por_pop_estados["pa"],barra_vertical)
#print(barra_vertical,lista_estados["pb"],lista_carac_estados["pb"],barra_vertical,lista_carac_resultado["pb"],lista_obitos_por_pop_estados["pb"],barra_vertical)
#print(barra_vertical,lista_estados["pe"],lista_carac_estados["pe"],barra_vertical,lista_carac_resultado["pe"],lista_obitos_por_pop_estados["pe"],barra_vertical)
#print(barra_vertical,lista_estados["pi"],lista_carac_estados["pi"],barra_vertical,lista_carac_resultado["pi"],lista_obitos_por_pop_estados["pi"],barra_vertical)
#print(barra_vertical,lista_estados["pr"],lista_carac_estados["pr"],barra_vertical,lista_carac_resultado["pr"],lista_obitos_por_pop_estados["pr"],barra_vertical)
#print(barra_vertical,lista_estados["rj"],lista_carac_estados["rj"],barra_vertical,lista_carac_resultado["rj"],lista_obitos_por_pop_estados["rj"],barra_vertical)
#print(barra_vertical,lista_estados["rn"],lista_carac_estados["rn"],barra_vertical,lista_carac_resultado["rn"],lista_obitos_por_pop_estados["rn"],barra_vertical)
#print(barra_vertical,lista_estados["rs"],lista_carac_estados["rs"],barra_vertical,lista_carac_resultado["rs"],lista_obitos_por_pop_estados["rs"],barra_vertical)
#print(barra_vertical,lista_estados["ro"],lista_carac_estados["ro"],barra_vertical,lista_carac_resultado["ro"],lista_obitos_por_pop_estados["ro"],barra_vertical)
#print(barra_vertical,lista_estados["rr"],lista_carac_estados["rr"],barra_vertical,lista_carac_resultado["rr"],lista_obitos_por_pop_estados["rr"],barra_vertical)
#print(barra_vertical,lista_estados["sc"],lista_carac_estados["sc"],barra_vertical,lista_carac_resultado["sc"],lista_obitos_por_pop_estados["sc"],barra_vertical)
#print(barra_vertical,lista_estados["se"],lista_carac_estados["se"],barra_vertical,lista_carac_resultado["se"],lista_obitos_por_pop_estados["se"],barra_vertical)
#print(barra_vertical,lista_estados["sp"],lista_carac_estados["sp"],barra_vertical,lista_carac_resultado["sp"],lista_obitos_por_pop_estados["sp"],barra_vertical)
#print(barra_vertical,lista_estados["to"],lista_carac_estados["to"],barra_vertical,lista_carac_resultado["to"],lista_obitos_por_pop_estados["to"],barra_vertical)
print(barra_horizontal*35)
